name: Metrics
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Install Node ⬇️
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies ⚙️
      run: npm install applicationinsights
    - name: Fetch repo clones and report 📈
      uses: actions/github-script@v7
      env:
        APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}
      with:
        github-token: ${{ secrets.GH_PAT }}
        script: |
          let appInsights = require('applicationinsights');
          appInsights.setup();

          clones = await github.rest.repos.getClones({
            owner: 'jandedobbeleer',
            repo: 'homebrew-oh-my-posh'
          });

          const isSameDay = (first, second) =>
            first.getFullYear() === second.getFullYear() &&
            first.getMonth() === second.getMonth() &&
            first.getDate() === second.getDate();
          const parseDate = (timestamp) => new Date(Date.parse(timestamp));
          const yesterday = ( d => new Date(d.setDate(d.getDate()-1)) )(new Date);

          yesterday_clones = clones.data.clones.find(clone => isSameDay(yesterday, parseDate(clone.timestamp)));

          let uniques = 0;
          if (yesterday_clones && typeof yesterday_clones.uniques === 'number') {
            uniques = yesterday_clones.uniques;
          } else {
            console.log("No clone data found for yesterday. Defaulting uniques to 0.");
          }

          console.log(uniques);

          let client = appInsights.defaultClient;
          client.trackMetric({name: "homebrew installs", value: uniques});



